apiVersion: v1
kind: Pod
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  containers:
    - name: product-service
      image: localhost:5000/product-service
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"